

[font]
size = 12

[font.bold]
family = "Hack"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "None"
opacity = 0.9

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 10
y = 10

[general]

import = [
  "~/dotfiles/alacritty/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
